version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - revive
    - staticcheck
  settings:
    revive:
      rules:
        - name: exported
    staticcheck:
      checks: ["all", "-SA1019"]
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        path: _test\.go$
    paths:
      - .*_test\.go$
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
